export const MOCK_COURSES = [
  {
    id: 1,
    courseName: "체육학개론",
    professor: "김교수",
    classification: "교양",
    department: "경제학과",
    year: "24학년",
    semester: "1학기",
  },
  {
    id: 2,
    courseName: "생활과건강",
    professor: "나교수",
    classification: "전공",
    department: "교육학과",
    year: "24학년",
    semester: "1학기",
  },
  {
    id: 3,
    courseName: "체육철학",
    professor: "박교수",
    classification: "전공",
    department: "농학과",
    year: "24학년",
    semester: "1학기",
  },
  {
    id: 4,
    courseName: "운동생리학",
    professor: "최교수",
    classification: "일반선택",
    department: "국어국문학과",
    year: "24학년",
    semester: "1학기",
  },
];
