name: Push source code to another repository

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: Create output
        run: sh ./build.sh
      - name: Push to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOYMENT_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: jbilee
          destination-repository-name: knous
          user-email: ${{ secrets.DEPLOYMENT_ACC }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY